# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_bucketlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('bucketlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bucketlist.Bucketlist')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
