# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_bucketlist', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
