# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_bucketlist', '0003_auto_20171023_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
    ]
